site_name: "${{ values.repoName }} Documentation"
site_description: "TechDocs site for ${{ values.repoName }}"
docs_dir: docs

nav:
  - Home: index.md
  - API: api.md
  - Getting Started: getting-started.md

plugins:
  - techdocs-core