apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.repoName }}
  namespace: ${{ values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.repoName }}
  template:
    metadata:
      labels:
        app: ${{ values.repoName }}
    spec:
      containers:
        - name: ${{ values.repoName }}
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: ${{ values.port }}
