apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ${{ values.repoName }}
  namespace: ${{ values.namespace }}
spec:
  to:
    kind: Service
    name: ${{ values.repoName }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect   # force HTTPS
