apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: DEPLOY_NAME_PLACEHOLDER
  namespace: ${{ values.namespace }}
spec:
  to:
    kind: Service
    name: DEPLOY_NAME_PLACEHOLDER
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect